Import MongoDownloader from utilix
XENONnT/fuse pull request #271
Opened 2024-10-11 17:54 UTC by yuema137

See this PR: https://github.com/XENONnT/utilix/pull/141

2024-10-12 15:16 UTC, dachengx requested changes
See below

2024-10-12 15:16 UTC, dachengx commented on pyproject.toml
> +utilix = "*"
This should be `">0.10.1"`

2024-10-14 20:46 UTC, dachengx approved these changes

2024-10-14 20:46 UTC, merged

2024-10-15 08:01 UTC, HenningSE commented
Thanks for the PR @yuema137 and @dachengx !